import { BRIKZ_COMPONENTS } from '@/brikz';
import { createBrikz } from '@rollers/libs-client-brikz';
import '../global.css';
import LayoutTop from '@/components/layout/top';
import LayoutHeader from '@/components/layout/header';
import LayoutMain from '@/components/layout/main';
import LayoutFooter from '@/components/layout/footer';
import LayoutBottom from '@/components/layout/bottom';

export const metadata = {
  title: 'Welcome to apps-client-portal-web',
  description: 'Generated by create-nx-workspace',
};

createBrikz({
  components: BRIKZ_COMPONENTS,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutHeader />
        <LayoutMain>{children}</LayoutMain>
        <LayoutFooter />
        <LayoutBottom />
      </body>
    </html>
  );
}
