import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import '../global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className="bg-gray-500">
        <NextIntlClientProvider>
        <div className="flex w-full h-full justify-center items-center">
          <div className="flex flex-col">
            <div className="flex-1">{children}</div>
          </div>
        </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
