import '../global.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-500">
        <div className="flex w-full h-full justify-center items-center">
          <div className="flex flex-col">
            <div className="flex-1">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
