import { BRIKZ_COMPONENTS } from '@/brikz';
import LayoutBottom from '@/components/layout/bottom';
import LayoutFooter from '@/components/layout/footer';
import LayoutHeader from '@/components/layout/header';
import LayoutMain from '@/components/layout/main';
import { createBrikz } from '@rollers/libs-client-brikz';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale } from 'next-intl/server';
import '../global.css';

export const metadata = {
  title: 'Welcome to apps-client-portal-web',
  description: 'Generated by create-nx-workspace',
};

createBrikz({
  components: BRIKZ_COMPONENTS,
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className="page">
        <NextIntlClientProvider>
          <LayoutHeader />
          <LayoutMain>{children}</LayoutMain>
          <LayoutFooter />
          <LayoutBottom />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
