import { BRIKZ_COMPONENTS } from '@/brikz';
import LayoutBottom from '@/components/layout/bottom';
import LayoutFooter from '@/components/layout/footer';
import LayoutHeader from '@/components/layout/header';
import LayoutHeaderSticky from '@/components/layout/header-sticky';
import LayoutMain from '@/components/layout/main';
import { createBrikz } from '@rollers/libs-client-brikz';
import '../global.css';

export const metadata = {
  title: 'Welcome to apps-client-portal-web',
  description: 'Generated by create-nx-workspace',
};

createBrikz({
  components: BRIKZ_COMPONENTS,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="frontpage">
          <LayoutHeaderSticky top={400}>
            <LayoutHeader />
          </LayoutHeaderSticky>
          <LayoutMain>{children}</LayoutMain>
          <LayoutFooter />
          <LayoutBottom />
      </body>
    </html>
  );
}
